const refs = {
  homeLink: document.getElementById('home'),
  discoverLink: document.getElementById('discover'),
  mainBox: document.querySelector('.main__box'),
  collectiblesBox: document.querySelector('.collectibles__box'),
  bidHeart: document.querySelectorAll('.bid_icon'),
  bidButton:document.querySelectorAll('.bid_button'),
  productBox: document.querySelector('.product__box'),
  productMoreButton: document.querySelector('.product__more_button'),
  productButtonList: document.querySelector('.product__minor_button_list'),
  productDescriptionButton: document.getElementById('description'),
  productDescription: document.querySelector('.product__minor_description_wrap'),
  productOffersButton: document.getElementById('offers'),
  productOffers: document.querySelector('.product__minor_offers_wrap'),
  productPriceHistoryButton: document.getElementById('price_history'),
  productPriceHistory: document.querySelector('.product__minor_price_history_wrap'),
  toTopBtn: document.querySelector('.button_to_top'),
};

export const {
  homeLink,
	discoverLink,
  mainBox,
  collectiblesBox,
  bidHeart,
  bidButton,
  productBox,
  productMoreButton,
  productButtonList,
  productDescriptionButton,
  productDescription,
  productOffersButton,
  productOffers,
  productPriceHistoryButton,
  productPriceHistory,
  toTopBtn,
} = refs;
