import "./js/refs";
import "./js/current";
import "./js/toogleHomePageBox";
import "./js/scroll";
import "./js/bid";
import "./js/pagination";
import "./js/product";
import "./js/notiflix";
import "./js/splide";